[www-client/epiphany] CFLAGS append gnu11
```ephy-filters-manager.c:207:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode```

This error occurs using <gcc-5 unless adjusted for. Because <gcc-5 is the current gentoo tree stable, this is a neccessary adjustment.